version: '3'

############### DOCKERS ##################
services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    # depends_on:
    #   - wordpress
    networks:
      - inception_network
    restart: always
    

  # wordpress:
  #   build: requirements/wordpress/
  #   container_name: wordpress
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - inception_network

  mariadb:
    build:
      context: requirements/mariadb/
      args:
      - DB_CLIENT=${DB_CLIENT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_MYSQL_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - inception_network
    volumes:
      - "database:/var/lib/mysql"
    networks:
      - inception_network
    restart: unless-stopped
    env_file:
      - ./.env
    


############### NETWORKS ##################

networks:
  inception_network:


############### VOLUMES ##################

volumes:
  website:
    driver_opts:
      type: none
      device: /home/mababou/data/wp
      o: bind
  database:
    driver_opts:
      type: none
      device: /home/mababou/data/db
      o: bind
   