version: '3'

services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    # depends_on:
    #   - wordpress
    networks:
      - inception_network
    restart: always
    

  # wordpress:
  #   build: requirements/wordpress/
  #   container_name: wordpress
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - inception_network

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - inception_network
    volumes:
      - "database:/var/lib/mysql"
    networks:
      - inception_network
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}


############### NETWORKS ##################

networks:
  inception_network:

############### VOLUMES ##################

volumes:
  website:
    driver_opts:
      type: none
      device: /home/mababou/data/wp
      o: bind
  database:
    driver_opts:
      type: none
      device: /home/mababou/data/db
      o: bind
   