version: "3"

############### DOCKERS ##################
services:

## Server ##
  nginx:
    container_name: nginx
    image: nginx:inception
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always
    
## Website ##
  wordpress:
    container_name: wordpress
    image: wordpress:inception
    build: requirements/wordpress/
    networks:
      - inception_network
    restart: always
    depends_on:
      - mariadb
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - TITLE=${TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}

## MySQL database ##
  mariadb:
    container_name: mariadb
    image: mariadb:inception
    build:
      context: requirements/mariadb/
      args:
      - DB_CLIENT=${DB_CLIENT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_MYSQL_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    container_name: mariadb
    hostname: ${DB_CLIENT}
    networks:
      - inception_network
    volumes:
      - "database:/var/lib/mysql"
    restart: always
    env_file:
      - ./.env
    


############### NETWORKS ##################

networks:
  inception_network:


############### VOLUMES ##################

volumes:
  website:
    driver_opts:
      type: none
      device: /home/mababou/data/wp
      o: bind
  database:
    driver_opts:
      type: none
      device: /home/mababou/data/db
      o: bind
   