version: '3'

services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    # depends_on:
    #   - wordpress
    networks:
      - inception_network
    restart: always
    

  # wordpress:
  #   build: requirements/wordpress/
  #   container_name: wordpress
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - inception_network


  # mariadb:
  #   build: requirements/mariadb/
  #   container_name: mariadb
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - inception_network

networks:
  inception_network:

volumes:
  website:
    driver_opts:
      type: none
      device: /home/mababou/data/wp
      o: bind
   