version: "3"

############### DOCKERS ##################
services:

## MySQL database ##
  mariadb:
    container_name: mariadb
    image: mariadb:inception
    build:
      context: requirements/mariadb/
      args:
      - DB_CLIENT=${DB_CLIENT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - network
    volumes:
      - "database:/var/lib/mysql"
    restart: always
    
## Website ##
  wordpress:
    container_name: wordpress
    image: wordpress:inception
    build: requirements/wordpress/
    networks:
      - network
    restart: always
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - TITLE=${TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
    volumes:
      - website:/var/www/html

## Server ##
  nginx:
    container_name: nginx
    image: nginx:inception
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    depends_on:
      - wordpress
    networks:
      - network
    restart: always


############### NETWORKS ##################

networks:
  network:


############### VOLUMES ##################

volumes:
  website:
    driver_opts:
      type: none
      device: /home/mababou/data/website
      o: bind
  database:
    driver_opts:
      type: none
      device: /home/mababou/data/database
      o: bind
   